-- Batch4_verification.sql
-- context_id: ctx-3a70562661bc
-- trace_id: trace-c4d7acea934f4bbbb5a8979a1de7051b
-- source_files: step4/A2_verification_checklist.md + module SQL object names
-- encoding: UTF-8

-- 1) 关键表存在性
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
  'PUBLIC_NOTICE',
  'PUBLIC_NOTICE_SCOPE',
  'PUBLIC_NOTICE_COVER',
  'PUBLIC_NOTICE_EXTERNAL_SOURCE',
  'PUBLIC_NOTICE_READ'
)
ORDER BY TABLE_NAME;

-- 期望值: 5
SELECT COUNT(1) AS expected_table_count_5
FROM USER_TABLES
WHERE TABLE_NAME IN (
  'PUBLIC_NOTICE',
  'PUBLIC_NOTICE_SCOPE',
  'PUBLIC_NOTICE_COVER',
  'PUBLIC_NOTICE_EXTERNAL_SOURCE',
  'PUBLIC_NOTICE_READ'
);

-- 2) 关键索引存在性（显式创建索引）
SELECT INDEX_NAME
FROM USER_INDEXES
WHERE INDEX_NAME IN (
  'IDX_PN_STATUS',
  'IDX_PN_PUBLISH_TIME',
  'IDX_PN_AUDIT_ORG',
  'IDX_PN_PUBLISHER_ORG',
  'IDX_PN_COMMUNITY',
  'IDX_PN_STREET',
  'IDX_PN_DIST',
  'IDX_PN_STATUS_AUDIT',
  'IDX_PN_TIME_RANGE',
  'IDX_PNS_SECT',
  'IDX_PNC_COVER',
  'IDX_PNC_NOTICE',
  'UNQ_PNR_NOTICE_USER',
  'IDX_PNR_USER',
  'IDX_PNR_NOTICE'
)
ORDER BY INDEX_NAME;

-- 期望值: 15
SELECT COUNT(1) AS expected_index_count_15
FROM USER_INDEXES
WHERE INDEX_NAME IN (
  'IDX_PN_STATUS',
  'IDX_PN_PUBLISH_TIME',
  'IDX_PN_AUDIT_ORG',
  'IDX_PN_PUBLISHER_ORG',
  'IDX_PN_COMMUNITY',
  'IDX_PN_STREET',
  'IDX_PN_DIST',
  'IDX_PN_STATUS_AUDIT',
  'IDX_PN_TIME_RANGE',
  'IDX_PNS_SECT',
  'IDX_PNC_COVER',
  'IDX_PNC_NOTICE',
  'UNQ_PNR_NOTICE_USER',
  'IDX_PNR_USER',
  'IDX_PNR_NOTICE'
);

-- 3) 配置对象核查（不含真实账号）
SELECT MENU_ID, MENU_NAME, PARENT_ID, MENU_URL
FROM SYS_MENU_INFO
WHERE MENU_ID IN (30837, 30838)
ORDER BY MENU_ID;

-- 角色菜单映射数量核查
SELECT MENU_ID, COUNT(1) AS role_menu_count
FROM SYS_ROLE_MENU
WHERE MENU_ID IN (30836, 30837, 30838)
GROUP BY MENU_ID
ORDER BY MENU_ID;

-- 重复映射核查（结果应为空）
SELECT ROLE_ID, MENU_ID, COUNT(1) AS dup_count
FROM SYS_ROLE_MENU
WHERE MENU_ID IN (30836, 30837, 30838)
GROUP BY ROLE_ID, MENU_ID
HAVING COUNT(1) > 1;
