-- Batch3_upgrade_and_config.sql
-- context_id: ctx-3a70562661bc
-- trace_id: trace-c4d7acea934f4bbbb5a8979a1de7051b
-- source_files: 08_upgrade_from_legacy.sql,10_menu_and_role_config.sql
-- encoding: UTF-8

-- >>> FILE: 08_upgrade_from_legacy.sql
-- ================================
-- 08_upgrade_from_legacy.sql
-- 兼容升级脚本：将旧版最小字段表升级为公告模块所需字段
-- 适用：Oracle/MySQL
-- 注意：若列已存在，请手动删除对应语句再执行
-- ================================

-- PUBLIC_NOTICE 补充缺失字段
ALTER TABLE PUBLIC_NOTICE ADD PUBLISHER_TYPE VARCHAR(32);
ALTER TABLE PUBLIC_NOTICE ADD PUBLISHER_ORG_ID VARCHAR(32);
ALTER TABLE PUBLIC_NOTICE ADD PUBLISHER_USER_ID VARCHAR(32);

ALTER TABLE PUBLIC_NOTICE ADD NOTICE_LEVEL VARCHAR(32);
ALTER TABLE PUBLIC_NOTICE ADD DIST_ID VARCHAR(32);
ALTER TABLE PUBLIC_NOTICE ADD STREET_ID VARCHAR(32);
ALTER TABLE PUBLIC_NOTICE ADD COMMUNITY_ID VARCHAR(32);

ALTER TABLE PUBLIC_NOTICE ADD STATUS VARCHAR(32);
ALTER TABLE PUBLIC_NOTICE ADD AUDIT_REQUIRED CHAR(1);
ALTER TABLE PUBLIC_NOTICE ADD AUDIT_ORG_ID VARCHAR(32);
ALTER TABLE PUBLIC_NOTICE ADD AUDIT_USER_ID VARCHAR(32);
ALTER TABLE PUBLIC_NOTICE ADD AUDIT_TIME VARCHAR(19);
ALTER TABLE PUBLIC_NOTICE ADD AUDIT_COMMENT VARCHAR(500);

ALTER TABLE PUBLIC_NOTICE ADD PUBLISH_TIME VARCHAR(19);
ALTER TABLE PUBLIC_NOTICE ADD START_TIME VARCHAR(19);
ALTER TABLE PUBLIC_NOTICE ADD END_TIME VARCHAR(19);

ALTER TABLE PUBLIC_NOTICE ADD TOP_FLAG CHAR(1);
ALTER TABLE PUBLIC_NOTICE ADD PUBLIC_ACCESS CHAR(1);

ALTER TABLE PUBLIC_NOTICE ADD STORAGE_TYPE VARCHAR(32);
ALTER TABLE PUBLIC_NOTICE ADD GS_CONTENT CLOB;
ALTER TABLE PUBLIC_NOTICE ADD RELA_TABLE VARCHAR(64);
ALTER TABLE PUBLIC_NOTICE ADD RELA_TAB_ID VARCHAR(64);
ALTER TABLE PUBLIC_NOTICE ADD LINK_URL VARCHAR(500);

ALTER TABLE PUBLIC_NOTICE ADD CREATE_TIME VARCHAR(19);
ALTER TABLE PUBLIC_NOTICE ADD UPDATE_TIME VARCHAR(19);

-- PUBLIC_NOTICE_READ 补充缺失字段
ALTER TABLE PUBLIC_NOTICE_READ ADD ID VARCHAR(32);
ALTER TABLE PUBLIC_NOTICE_READ ADD CREATE_TIME VARCHAR(19);

-- 如需索引，请执行 06_create_index.sql


-- >>> FILE: 10_menu_and_role_config.sql
-- =============================================================================
-- 公示公告模块菜单和权限配置
-- 执行顺序：先执行本文件，再验证菜单显示
-- 执行时间：2026-02-05
-- =============================================================================
-- =============================================================================
-- 第一部分：菜单配置
-- =============================================================================
-- 1. 公告管理（发布入口）
INSERT INTO SYS_MENU_INFO (
        MENU_ID,
        CLIENT_NO,
        MENU_NAME,
        PARENT_ID,
        MENU_URL,
        MENU_ICON,
        OPER_USER,
        MENU_LEVEL,
        TM_SMP,
        SORT_NUM,
        IS_HOME,
        HOME_ICON
    )
VALUES (
        30837,
        'HYJG_CLIENT',
        '公告管理',
        30836,
        '/pages/backstage/notice/index.xhtml',
        'fa-edit',
        '10000',
        2,
        '20260205',
        1,
        0,
        ''
    );
-- 2. 公告审核（社区审核入口）
INSERT INTO SYS_MENU_INFO (
        MENU_ID,
        CLIENT_NO,
        MENU_NAME,
        PARENT_ID,
        MENU_URL,
        MENU_ICON,
        OPER_USER,
        MENU_LEVEL,
        TM_SMP,
        SORT_NUM,
        IS_HOME,
        HOME_ICON
    )
VALUES (
        30838,
        'HYJG_CLIENT',
        '公告审核',
        30836,
        '/pages/backstage/notice/audit_index.xhtml',
        'fa-check-square-o',
        '10000',
        2,
        '20260205',
        2,
        0,
        ''
    );
-- =============================================================================
-- 第二部分：角色菜单权限配置
-- =============================================================================
-- 行业监管-管理员 (40210) - 全部菜单
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40210, 30836, '20260205');
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40210, 30837, '20260205');
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40210, 30838, '20260205');
-- 行业监管-市局 (40211) - 公告管理
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40211, 30836, '20260205');
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40211, 30837, '20260205');
-- 行业监管-区局 (40212) - 公告管理
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40212, 30836, '20260205');
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40212, 30837, '20260205');
-- 行业监管-街道 (40213) - 公告管理
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40213, 30836, '20260205');
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40213, 30837, '20260205');
-- 行业监管-社区 (40214) - 公告管理 + 公告审核
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40214, 30836, '20260205');
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40214, 30837, '20260205');
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40214, 30838, '20260205');
-- 行业监管-业委会 (40230) - 公告管理
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40230, 30836, '20260205');
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40230, 30837, '20260205');
-- 行业监管-物业公司 (40240) - 公告管理
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40240, 30836, '20260205');
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40240, 30837, '20260205');
-- 行业监管-项目经理 (40241) - 公告管理
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40241, 30836, '20260205');
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID, TM_SMP)
VALUES (40241, 30837, '20260205');
COMMIT;
